import type { Metadata } from "next";
import "./globals.scss";


export const metadata: Metadata = {
  title: {
    template: "%s | Haushaltsbuch", // %s gets replaced by child page titles
    default: "Haushaltsbuch",       // Fallback for homepage
  },
  description: "Generated by create next app",
};

/**
 * Root layout that wraps every page in the html and body tags.
 * @param props - The page content as `children`
 * @returns The HTML document shell
 */
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>{children}</body>
    </html>
  );
}
